### ISSUE TITLE
Cannot find "base.htm"

### ISSUE THREAD

**Issue by JSusnik-Pollard** [djangoaddicts/django-pygwalker#16]
I'm trying to use the generic pygwalker view (users upload CSV), and I'm getting a template error; cannot find "base.htm"

I'm relatively new to Django, so I apologize if I'm missing an obvious step, but I've looked through the source files and I cannot find a "base.htm" anywhere outside of the /tests/ directory.

**Comment by davidslusser** [comment]
The template in the pygwalker view is looking to extend a base template named "base.htm" by default. You can add an entry to your settings file to change to your preferred base template like so: `BASE_TEMPLATE = "my_base_template.htm"`
